### ISSUE TITLE
Kimetsu no Yaiba Post-QC

### ISSUE THREAD

**Issue by Lann094** [Kaleido-subs/Kaleidosubs#2]
**01**
> Dialogue: 10,0:01:45.54,0:01:51.04,Default,,0,0,0,,{\q2}He won’t be able to give you a ride if \Nyou’re tired since he can’t use the cart today.

Bit of word mince... Grammatically you need a comma, but could do with a shortening. It took me about 3 reads to understand it.

> Dialogue: 10,0:06:46.30,0:06:48.05,Default,,0,0,0,,I’m cutting the lights.

Maybe a nitpick, but this felt off for the period.

> Dialogue: 10,0:18:34.38,0:18:36.38,Default,,0,0,0,,{\i1}Because for them, humans are nutritious.

Didn't read right to me. Maybe something more like "sustenance".

**02**
> Dialogue: 10,0:15:43.67,0:15:50.26,Default,,0,0,0,,N-Now have I... p-passed the test?

Timing's real long. Could split it up, maybe even a few times, for effect.

> To Be Continued sign

Probably a big ask, but it'd be cool to see some TS wizardry to get closer to the つづく.

**03**
> Dialogue: 10,0:02:30.00,0:02:32.42,Default,,0,0,0,,Their staple food are humans.

"is" humans.

**04**
> Dialogue: 10,0:17:38.99,0:17:41.87,Default,,0,0,0,,It’s like Urodaki fed them to me!

Urokodaki.

> Dialogue: 10,0:18:39.76,0:18:42.72,Default,,0,0,0,,Another of Urokodaki’s brats is gonna die.

I don't presume to be a TL, but I'm hearing 死んだ. I interpreted it as he thought he was dead, which is why he was so surprised when he dodged the attack.

**05**

> Dialogue: 10,0:07:00.56,0:07:02.40,Default,,0,0,0,,{\i1}If I ended up dying,
Dialogue: 10,0:07:02.40,0:07:04.32,Default,,0,0,0,,{\i1}my soul would make it back there, too.

Tense felt a little off. I'm understanding it as "If I die, my soul will make it back there too."

**Comment by Lann094** [comment]
**07**
> Dialogue: 10,0:17:17.51,0:17:19.97,Default,,0,0,0,,I-I beg your pardon!

Issue with this phrase is the double meaning... I typically only hear it in the latter usage here https://dictionary.cambridge.org/us/dictionary/learner-english/i-beg-your-pardon but is probably a taste thing.

**08**
> Dialogue: 10,0:20:03.22,0:20:11.60,Default,,0,0,0,,{\q2}A demon with a high concentration of Kibutsuji’s blood \N means a demon closer in strength to Kibutsuji himself.

I wasn't sure there was really a comparison here to warrant the "closer". Seemed like it should just be "close".

**09**

Not really an issue, but for the record, I didn't know what a temari was. Just had to guess by context. Dunno if it's something that should be localised heavier.

**10**

> Dialogue: 10,0:07:29.63,0:07:33.47,Default,,0,0,0,,{\q2}All I used  on her was a healing serum \Nmade exclusively for demons.

Double space. (Git quote is squashing it)

> Dialogue: 10,0:12:11.87,0:12:14.83,Default,,0,0,0,,They can’t inflict fatal wounds to each other.

Instinct tells me this should be "on" each other.

**Comment by Lann094** [comment]
**13**
> Dialogue: 10,0:05:53.33,0:05:56.96,Default,,0,0,0,,You’re just wasting paper and fountain pens!

I think all pens of this period were fountain pens? Not sure though, just stood out.

**15**
> Chuntarou's signs during preview

Yeah, crashed Plex on my TV.

**18**
> Dialogue: 10,0:14:51.66,0:14:54.49,Default,,0,0,0,,{\i1}You{\i0} are the one know who’s not making sense!

Uh, yeah.

**Comment by LightArrowsEXE** [comment]
Thanks for the notes, Lann. I have gone over them back when they were posted, but I forgot to close this issue.
